services:
# My grafana service 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    expose:
      - "3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - grafana
    restart: unless-stopped

volumes:
  grafana-storage: